namespace AIMaid.Contracts;

public static class BusinessRoutes
{
    public const string ChatSend = "chat.send";
    public const string ChatHistory = "chat.history";
    public const string CharacterList = "character.list";
    public const string CharacterGet = "character.get";
    public const string CharacterUpdate = "character.update";
    public const string CharacterSelect = "character.select";
    public const string CharacterPresent = "character.present";
    public const string SettingsGet = "settings.get";
    public const string SettingsSave = "settings.save";
    public const string TaskStatus = "task.status";
    public const string TaskList = "task.list";
    public const string TaskCancel = "task.cancel";
    public const string ComfyUiGenerate = "comfyui.generate";
    public const string DownloadStart = "download.start";
    public const string TtsSpeak = "tts.speak";
    public const string AsrTranscribe = "asr.transcribe";
    public const string FileMove = "file.move";
    public const string FileDelete = "file.delete";
    public const string MediaLaunch = "media.launch";
    public const string AgentExecute = "agent.execute";
    public const string AgentCapabilitiesList = "agent.capabilities.list";
    public const string AgentCapabilitySave = "agent.capability.save";
    public const string ProactiveEvaluate = "proactive.evaluate";
    public const string ProactiveRulesList = "proactive.rules.list";
    public const string ProactiveRuleSave = "proactive.rule.save";
    public const string DisturbanceSettingsGet = "disturbance_settings.get";
    public const string DisturbanceSettingsSave = "disturbance_settings.save";
    public const string ReminderSave = "reminder.save";
    public const string ReminderList = "reminder.list";
    public const string ReminderDelete = "reminder.delete";
    public const string ReminderProcessDue = "reminder.process_due";
    public const string NotebookSave = "notebook.save";
    public const string NotebookList = "notebook.list";
    public const string NotebookDelete = "notebook.delete";
    public const string VaultSave = "vault.save";
    public const string VaultGet = "vault.get";
    public const string VaultList = "vault.list";
    public const string VaultDelete = "vault.delete";
    public const string MarketRecord = "market.record";
    public const string MarketList = "market.list";
    public const string VideoSave = "video.save";
    public const string VideoList = "video.list";
    public const string RemoteSiteSave = "remote_site.save";
    public const string RemoteSiteList = "remote_site.list";
    public const string RemoteMediaResolve = "remote_media.resolve";

    public const string ChatDelta = "chat.delta";
    public const string ChatCompleted = "chat.completed";
    public const string TaskProgress = "task.progress";
    public const string TaskCompleted = "task.completed";
    public const string DownloadProgress = "download.progress";
    public const string ErrorOccurred = "error.occurred";
    public const string AgentApprovalRequested = "agent.approval_requested";
    public const string AgentToolCallCompleted = "agent.tool_call_completed";
    public const string ProactiveDecision = "proactive.decision";
    public const string ReminderDue = "reminder.due";
    public const string TtsAudioReady = "tts.audio_ready";
    public const string CharacterPresentation = "character.presentation";
    public const string SettingsChanged = "settings.changed";
    public const string CharacterChanged = "character.changed";
}
